config/routes.rb
Dealyzator::Application.routes.draw do
  get "users/index"
  devise_for :users
  resources :dashboard
  resources :homescreen
  root to: 'homescreen#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :firstname, presence: true, length: { maximum: 15 }
  validates :lastname, presence: true, length: { maximum: 20 }
  before_save { |user| user.firstname = firstname.capitalize }
  before_save { |user| user.lastname = lastname.capitalize }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname,:email, :password,  :password_confirmation) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:firstname, :lastname,:email, :password,  :password_confirmation, :current_password) }
	end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

before_filter :authenticate_user!

	def index
	end
	
end

app/controllers/homescreen_controller.rb
class HomescreenController < ApplicationController
	
	def index
		if user_signed_in?
			redirect_to controller: :dashboard, action: :index
		end
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
		@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homescreen_helper.rb
module HomescreenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<div class="forms">
        <p><span class="forms-text">Построить социальную сеть активных людей</span></p>
        <select class="form-control forms-css">
          <option selected>Выбранная цель:</option>
          <option>Сайт</option>
          <option>Джава скрипт</option>
          <option>Энифинг элс</option>
          <option>Лорем ипсум долор</option>
        </select>
        
        <p><span class="forms-text-no-color">Цель дня: Здесь выбираем цель сегодняшнего дня</span></p>
        <select class="form-control forms-css">
          <option>Моя группа</option>
          <option>Его группа</option>
          <option>Её группа</option>
          <option>Их группа</option>
          <option>Наша группа</option>
        </select>
        
    </div>
    
	<div class="layout">
       <div class="left-column">
       		<div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">А: Обязательно (День)</div>
        

        <!-- Table -->
        <table class="table">
          <thead>
            <tr>
              <th class="number">#</th>
              <th class="challenge">Задача</th>
              <th class="status">Статус</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Задача номер раз</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
            <tr>
              <td>2</td>
              <td>Задача номер два два два</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
            <tr>
              <td>3</td>
              <td>№3</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
          </tbody>
        </table>
      </div>
      
      
      	<div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">А: Обязательно (День)</div>
        

        <!-- Table -->
        <table class="table">
          <thead>
            <tr>
              <th class="number">#</th>
              <th class="challenge">Задача</th>
              <th class="status">Статус</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Задача номер раз</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
            <tr>
              <td>2</td>
              <td>Задача номер два два два</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
            <tr>
              <td>3</td>
              <td>№3</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
          </tbody>
        </table>
      </div>
      
      
      
      	<div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">А: Обязательно (День)</div>
        

        <!-- Table -->
        <table class="table">
          <thead>
            <tr>
              <th class="number">#</th>
              <th class="challenge">Задача</th>
              <th class="status">Статус</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>Задача номер раз</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
            <tr>
              <td>2</td>
              <td>Задача номер два два два</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
            <tr>
              <td>3</td>
              <td>№3</td>
              <td class="check"><input type="checkbox"></td>
            </tr>
          </tbody>
        </table>
      </div>
       
       
       
       </div>
       
       
       
       
       
       <div class="center-column">
       	<div class="panel panel-primary">
          <!-- Default panel contents -->
        <!-- Table -->
        <table class="table">
          <tbody>
            <tr>
              <td class="time">10:00 - 11:00</td>
              <td>Задача номер раз</td>
            </tr>
            <tr>
              <td class="time">11:00 - 12:00</td>
              <td>Задача номер два два два</td>
            </tr>
            <tr>
              <td class="time">12:00 - 13:00</td>
              <td>№3</td>
            </tr>
             <tr>
              <td class="time">10:00 - 11:00</td>
              <td>Задача номер раз</td>
            </tr>
            <tr>
              <td class="time">11:00 - 12:00</td>
              <td>Задача номер два два два</td>
            </tr>
            <tr>
              <td class="time">12:00 - 13:00</td>
              <td>№3</td>
            </tr>
             <tr>
              <td class="time">10:00 - 11:00</td>
              <td>Задача номер раз</td>
            </tr>
            <tr>
              <td class="time">11:00 - 12:00</td>
              <td>Задача номер два два два</td>
            </tr>
            <tr>
              <td class="time">12:00 - 13:00</td>
              <td>№3</td>
            </tr>
             <tr>
              <td class="time">10:00 - 11:00</td>
              <td>Задача номер раз</td>
            </tr>
            <tr>
              <td class="time">11:00 - 12:00</td>
              <td>Задача номер два два два</td>
            </tr>
            <tr>
              <td class="time">12:00 - 13:00</td>
              <td>№3</td>
            </tr>
             <tr>
              <td class="time">10:00 - 11:00</td>
              <td>Задача номер раз</td>
            </tr>
            <tr>
              <td class="time">11:00 - 12:00</td>
              <td>Задача номер два два два</td>
            </tr>
            <tr>
              <td class="time">12:00 - 13:00</td>
              <td>№3</td>
            </tr>
             <tr>
              <td class="time">10:00 - 11:00</td>
              <td>Задача номер раз</td>
            </tr>
            <tr>
              <td class="time">11:00 - 12:00</td>
              <td>Задача номер два два два</td>
            </tr>
            <tr>
              <td class="time">12:00 - 13:00</td>
              <td>№3</td>
            </tr>
          </tbody>
        </table>
        </div>
               
       </div>
       
       
       
       <div class="right-column">
          
       	<div class="calendar">
         <ul class="nav nav-pills">
              <li class="active"><a href="#">День</a></li>
              <li><a href="#">Неделя</a></li>
              <li><a href="#">Месяц</a></li>
         </ul>
        <%= image_tag "calendar.png" %>
        </div>
       
       </div>
    </div>

app/views/homescreen/index.html.erb
<div class="container">
<div class="center hero-unit">
	<h1>Welcome to WebSite!</h1>
	<h2><i>I think you should sign up!</i></h2>
	<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dealyzator</title>
  <meta charset="utf-8" />
  <meta name="keywords" content="" />
	<meta name="description" content="" />
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="wrapper">
			<header class="header">
				<nav class="navbar navbar-default" role="navigation">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Dealyzator", root_path, class: "navbar-brand" %>
          </div>
        
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Users",    users_index_path %></li>
              <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My account<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit my profile", edit_user_registration_path %></li>
									<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                  <li class="divider"></li>
                  <li><a href="#">Separated link</a></li>
                  <li class="divider"></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <% else %>	
								<li><%= link_to "Sign in", new_user_session_path %></li>
							<% end %>
            </ul>
          </div><!-- /.navbar-collapse -->
        </nav>
	</header><!-- .header-->
    <%= yield %>
		<footer class="footer">
		</footer>
	</div><!-- .wrapper -->
</body>
</html>

app/views/users/index.html.erb
<div class="container">
<h1>Users#index</h1>
<table class="table">
  <tr>
		
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>ID</th>
  
  </tr>

<% @users.each do |user| %>
  <tr >
		
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>
    <td><%= user.id %></td>
   

  </tr>
<% end %>
</table>
</div>